import './styles/reset.css';
import './styles/document.css';
import './styles/colors.css';
import './styles/grid.css';
import './styles/misc.css';
import './styles/font/anton.css';
import './styles/font/digital7.css';
import './styles/typography.css';
import './App';
